- app/db/knexfile.js
- components/edit-team-form.js
- components/form-map.js
- package.json
- pages/_app.js
- yarn.lock
this pr:
- adds leaflet-control-geocoder
- lets users geocode on the team edit map to find places easier
this pr also makes a few little fixes that can be reverted if needed:
- moves `pg.defaults.ssl = false` to a line that works for both development & test cases. there might be a better way to handle this, but in the case where the node env is development and the database url env isn't being set `pg.defaults.ssl = true` doesn't work.
- removes an unneeded attribute in the team edit form
- uses `crossOrigin` instead of `crossorigin` in a stylesheet link because apparently that was throwing an error in react
currently nominatim is being used as the geocoder. we might want to make that configurable.
closes #57
> use leaflet-control-geocoder to provide a geocoder on the team edit map

- components/sidebar.js
quick fix to resolve `Router.push` not being a function when we try to log out
> fix logout

- pages/profile.js
Small fix so that the create team button links to `/teams/create` rather than use our old placeholder function.
> replace placeholder createTeam function with link to /teams/create

- app/manage/index.js
- app/manage/permissions/index.js
- app/manage/permissions/join-team.js
- app/manage/teams.js
- app/tests/permissions/join-team.test.js
- lib/teams-api.js
- pages/team.js
closes #80 
This adds a button for authenticated users to the team view page letting them join the team if they are not already in it.
It also adds a `Sign in to join team` button if the user has not yet logged in.
All this is accomplished with an endpoint at `/api/teams/:id/join` that takes the user id of the current session and adds them to the team if allowed by the `team:join` permission. This is distinct from the endpoints for adding/updating members because it is assumed those are requested by team moderators. I think it makes sense for `join` to be separate.
If the user signs in with the `Sign in to join team` button it does not redirect them back to the team page. I think that would be an important thing to add. I am not yet sure how to accomplish that with this login flow, …
> authenticated users can join public teams

- app/db/knexfile.js
- package.json
- yarn.lock
- Upgrade Knex to 0.20, which supports the latest version of pg-connection-string. Postgresql connection urls with the parameter `sslmode` are supported: `postgres://postgres@host.docker.internal/osm-teams?sslmode=disable`
- Remove workaround which was setting `pg.defaults.ssl`.
Closes #136 
Supersedes #124 
@kamicut  
- Does knexfile.js look OK to you now? I am able to start the app and `yarn run migrate` and `yarn run test` all OK for me. 
- Does the beta deployment environment specify `sslmode` on it's `DSN` environment variable? If not, this could break it because the ssl default is no longer being set. I think we should strive for making these settings explicit and not depending on `pg.defaults.ssl` if possible.
> Use postgresql connection url parameter with knex 0.20

- app/db/knexfile.js
- app/db/migrations/20200130150202_team-moderator-unique.js
- app/db/migrations/20200130155125_team-member-unique.js
- app/lib/team.js
- app/manage/index.js
- app/manage/teams.js
- app/tests/api/team-api.test.js
- app/tests/api/team-model.test.js
- docker-compose.dev.yml
- docker-compose.yml
- docs/api.md
- docs/api.yml
- package.json
- yarn.lock
Builds upon existing database schema and api implementation to add 2 new api endpoints:
```
/api/teams/:id/assignModerator/:osmId
/api/teams/:id/removeModerator/:osmId
```
Closes #127
> Team moderators can assign other users as moderators

- .gitignore
- app/lib/team.js
- app/manage/index.js
- app/manage/permissions/index.js
- app/manage/teams.js
- app/tests/api/team-api.test.js
- Add new route /api/my/teams which returns teams the authenticated user is a member of, and teams they moderate (if any).
- Add unit test.
- Add `team.listModeratedBy`.
- Rename permission `public` to `public-authenticated`
I tested this by using a bearer token from the cli, for example:
```bash
curl -H "Authorization: Bearer $OSM_TEAMS_BEARER_TOKEN" http://localhost:8989/api/my/teams | jq .
```
Closes #145
> New API route for "my teams" and "my moderated teams"

- app/lib/team.js
- app/manage/organizations.js
- app/manage/teams.js
- app/manage/utils.js
- app/tests/api/organization-api.test.js
- app/tests/api/team-api.test.js
- app/tests/api/team-model.test.js
- docs/api.yml
- package.json
- yarn.lock
> Add member and moderator ids to listTeams response.

- app/lib/team.js
- Fixes a bug caused by #173
- listMembers() and listModerators() should not join with users table
(they are just osm users, but probably not app users)
> Fix members and moderators in listTeams response.

- bin/managers.sh
- bin/organizations.sh
- bin/owners.sh
Add bash scripts for add+remove of organizations, org owners, and org managers.
Closes #177
```bash
export DSN=postgres://postgres@localhost/osm-teams?sslmode=disable
./organizations ...
./owners ...
./managers ...
```
> shell scripts for organization management

- app/db/migrations/20220222155039_add_badges.js
- app/db/migrations/20220302104250_add_user_badges.js
- app/lib/profile.js
- app/manage/badges.js
- app/manage/index.js
- app/manage/utils.js
- app/tests/api/badges-api.test.js
- app/tests/api/organization-api.test.js
- app/tests/api/organization-model.test.js
- app/tests/api/profile-api.test.js
- app/tests/api/profile-model.test.js
- app/tests/api/team-api.test.js
- app/tests/api/team-model.test.js
- app/tests/utils.js
- package.json
- yarn.lock
API routes for managing and fetching organization badges.
This is WIP. To do list:
Other notable changes introduced:
- Schema validation with Yup
- All tables are dropped at spec start, for two reasons:
- Rolling back after the spec might not happen and break next spec run
- In case test fails, data will be still available in `test-db` for inspection
Running tests, doc review.
- https://github.com/developmentseed/osm-teams/issues/240
> Add badges routes

- app/manage/badges.js
- app/manage/index.js
- app/tests/api/badges-api.test.js
- components/button.js
- package.json
- pages/badges/assign.js
- pages/badges/edit.js
- yarn.lock
This contributes to #240 by adding a page to add/update badges assignment. How to test:
- Create/view org
- Add members and/or staff
- Create badge at org page
- Open badge page by clicking it in badges table in org page
- Enter OSM id or username in assign input, hit enter
- If user is not part of organization a toast will be displayed
- If user is part of org, badge assignment page is open
- Set dates and submit, toast will be displayed on success/error
@kamicut there is a failing test related to API validation, but I think this is ready for a first review.
> Improve badge assignment

- components/table.js
- pages/organization.js
If no data is passed to the table component it will render only the header (with no rows), which is not desirable. In this PR the table component is changed to display a empty state message if no data is passed. As this message is customizable, it is possible to pass a 'Loading...' message when the data is being fetched.
Added a <td> containing `emptyStateMessage` that spans to all columns when no data is available.
At the moment this is applied only to organization page, which can be tested by visiting it. Other tables should keep working as before, but now displaying "No data available" if no rows are available. We should use this elsewhere if necessary.
There was no ticket for this bug.
> Add empty state to table component

- app/manage/badges.js
- app/manage/index.js
- pages/badges/assign.js
- pages/organization.js
Contributes to #240. Changes:
- Add "Assign a badge" action in profile page actions (when clicked in organization page)
- Badge assignment page allow selecting which badge to apply
- Badge assignment page now includes a button to unassign a badge
How to test: 
- Assign a badge: go to an organization page that has badges, click any member/staff user, click gear button, select "Assign a badge". This will redirect to the badge assignment page, then select a badge and click assign button. 
- Unassign a badge: in the organization page, click the badge assigned to the user, at badge page click user in assigned members table, hit unassign button at badge assignment page
Know issues:
- Workflow to update/remove badge is not ideal, we should list assigned badges in user profile and link it to the …
> Improve badge assignment, add badge unassignment

- app/db/migrations/20220415114820_invitations.js
- app/lib/team.js
- app/manage/index.js
- app/manage/teams.js
- lib/teams-api.js
- pages/invitation.js
- pages/team.js
- This PR introduces invitation links for teams so that moderators can send a URL to a user or group of users without having to add them by OSM ID.
- I added a new page for "invitation request" that a logged-in user can accept
- In the teams settings, a moderator can "request an invite link" which will generate a UUID at the API level that corresponds to a valid invitation
1. Go to any team as a moderator and click on "Create invite link" which will generate a URL
2. With a secondary user, go to the newly created invite link and accept the invitation
3. The secondary user should now be part of the team
- #81 is a similar issue
> Invite Links

- app/lib/osm.js
- Fix login bug where a new login flow (after cookie expiry) would overwrite the profile of a user because they re-authenticated with OpenStreetMap
- After re-authentication, we merge the incoming profile of the user with the profile in the database and continue the flow
- We can force re-authentication with OpenStreetMap using two incognito windows. Try logging into one incognito window and filling out a team profile. In the second window, if you login again you should see the same profile values (they are not overwritten).
> fix login profile bug

- app/manage/index.js
- Fix the API permissions for the `org/:id/teams` call
- We add the `can('organization:view-members')` permission to this API call: if an org is public, you can view its teams and members, otherwise you have to be a member of the org
- Try calling the API for a private org with a non-org member
- closes #274
> Fix for org/teams API permissions

- app/manage/permissions/view-team-members.js
- pages/invitation.js
- pages/login.js
- Fixes invitation link page where it would let you click on "join a team" if you're not logged in
- Fix permission where an organization owner cannot view members of a private team within an org
> Permission fixes

- app/lib/organization.js
- app/manage/index.js
- app/manage/permissions/index.js
- app/manage/permissions/view-org-team-keys.js
- components/edit-team-form.js
- lib/profiles-api.js
- pages/team-edit.js
Contributes to #286. I was able to replicate the error by adding a moderator user that is not part of the organization. If the user is part of the org, team profile editing works.
How to test:
- Create a org
- Add team to org
- Add a moderador user to team and not to the org
- Visit team edit page with moderador user, they should be able to edit profile
cc @kamicut
> Fix access of team moderator to profile keys

- app/manage/teams.js
Creates a code guard for empty `teamData` object so that update only happens when there is data. Closes #285
> Fixes #285

- app/db/migrations/20221121094350_drop-hashtag-uniqueness.js
There is a constraint forbidding different teams to have the same hashtag. This was introduced in the early stages of OSM Teams, but it doesn't seem necessary at the moment. This contributes to #308.
This change will affect OSM Teams v1. If this works we can add the same migration file to v2.
cc @kamicut
> Drop hashtag uniqueness

- next.config.js
Ideally, we should do away with `publicRuntimeConfig` and `serverRuntimeConfig` because they are deprecated. This PR allows us to use preview deploys by setting the APP_URL to the Vercel URL when deploying there.
> add vercel url to config

- app/index.js
- pages/_app.js
- pages/maintenance.js
This adds an environment variable "MAINTENANCE_MODE" that will render a simple maintenance page on all pages and API routes.
To test, run `MAINTENANCE_MODE=true yarn dev` and access any route.
@batpad @kamicut ready for review.
> Add maintenance mode to v1

- .github/workflows/test.yml
- src/pages/api/organizations/[orgId]/teams.js
- src/pages/api/swagger.js
The pull request #344 was closed because I deleted the target branch and there is no way of reopening it. This one replaces it.
This contributes to https://github.com/developmentseed/osm-teams/issues/254 and https://github.com/developmentseed/osm-teams/issues/171.
I added the full contents of the Yaml swagger file from v1 to /src/api/swagger.js and now all routes should have at least the same documentation that was available on v1. I added a comment about the documentation approach introduced by next-swagger-docs, which avoids having one big file and keeps the documentation close to implementation. This is the approach already used in src/pages/api/organizations/[orgId]/teams.js.
To test this, run `yarn dev` and visit http://127.0.0.1/docs/api.
@kamicut @batpat ready for review.
> Fix API docs

- migrations/20221216122421_username_table.js
- src/components/profile-modal.js
- src/lib/logger.js
- src/models/team.js
- tests/api/cache.test.js
This allows us to cache requests to OSM in a username table. I've added an updated_at table column so that we can run a subroutine to backfill missing usernames and also update them on a regular basis from OSM. For example, we could have a subroutine that picks the 10 least recent and request the usernames from OSM and update the database every x minutes.
> Add username table

- src/models/team.js
Some parts of the app call the function `Team.resolveMemberNames` with an array of strings, which causes an error updating username caching. Adding a team member is failing because of this.
I added a fix to ensure user ids are integers. Ideally, we should add test coverage property types on Models.
This contributes to #298 and #355.
To test, visit a team member page and try adding a member.
@kamicut ready for review.
> Make sure user ids are integers when resolving member names

- src/pages/organizations/[id]/badges/[badgeId]/index.js
- src/pages/organizations/[id]/badges/add.js
Contributes to #358 by avoiding breaking the badge page. This also fix the badge creation page, which was broken.
@kamicut ready for review
> Fix data fetching on badge page

- .env.test
- next.config.js
- src/middlewares/base-handler.js
- src/middlewares/can/authenticated.js
- src/pages/api/auth/[...nextauth].js
- src/pages/api/introspect.js
- src/pages/api/my/teams.js
- tests/api/team-api.test.js
- tests/utils/create-agent.js
- tests/utils/get-session-token.js
This implements:
1. token extraction from authorized API calls that have `Bearer <access_token>`
2. checks if the access token is valid by sending it to the `/introspect` route in the auth proxy (check https://github.com/developmentseed/osm-teams/commit/5470dc55bcf3ae808e5dfc22f6173ae01987b741)
3. extracts the `sub` trait from the resulting token and adds it to the session
This will allow API calls from third party applications to use access tokens to authenticate with the API.
I also added `isAuthenticated` for routes that need simply to have the session and session user ids in the `can` middleware.
> Token Validation for API calls, fix #354

- cypress.config.js
- cypress/e2e/organizations/badges.cy.js
- src/components/tables/users.js
- src/models/badge.js
- src/models/organization.js
- src/pages/organizations/[id]/index.js
Add a badges column to the org members table at organization view. Contributes to #295, built on top of #378.
@LanesGood badges need styling, this is ready for a first review.
> Add badges to org members table

- cypress/e2e/organizations/badges.cy.js
- src/components/badge.js
- src/components/tables/users.js
Limits badges to 3 in members table to avoid overflow, with indicator for extra badges:
> Limit badges column to 3 badges in users table

- src/components/button.js
- src/components/pagination.js
Minor style change to distinguish active page in pagination.
@willemarcel I also notice that pagination options are behaving strangely when there are only 2 pages. See below screenshot. Changing the `PAGE_INDEX_START` const to 0 didn't seem to help adjust this, though I see that we 0-indexed other examples of this pattern. Any ideas?
> Update pagination button styles

- src/components/button.js
- src/components/edit-team-form.js
- src/components/layout.js
- src/components/profile-form.js
- src/components/profile-modal.js
- src/components/sidebar.js
- src/components/tables/table.js
- src/pages/_document.js
- src/pages/index.js
- src/pages/organizations/[id]/badges/[badgeId]/index.js
- src/pages/organizations/[id]/edit.js
- src/pages/organizations/[id]/index.js
- src/pages/teams/[id]/edit.js
- src/pages/teams/[id]/index.js
- src/pages/teams/create.js
- src/pages/teams/index.js
This PR makes a number of small style changes that overall have a larger effect. I began looking at responsive styles for tables and pages, and then moved to making styles more consistent across the board, and then ended up making some more changes.
Screenshots:
> Update table, page and layout styles

- src/components/button.js
- src/components/edit-org-form.js
- src/components/edit-team-form.js
- src/components/profile-form.js
- src/components/sidebar.js
- src/pages/organizations/[id]/badges/[badgeId]/assign/[userId].js
- src/pages/organizations/[id]/badges/[badgeId]/index.js
- src/pages/organizations/[id]/badges/add.js
- src/pages/organizations/[id]/badges/assign/[userId].js
- src/pages/organizations/[id]/edit-privacy-policy.js
- src/pages/organizations/[id]/edit-profiles.js
- src/pages/organizations/[id]/edit-team-profiles.js
- src/pages/organizations/[id]/edit.js
- src/pages/organizations/[id]/index.js
- src/pages/teams/[id]/edit-profiles.js
- src/pages/teams/[id]/edit.js
- src/styles/theme.js
This PR:
- Adds "Back Links" to previous/parent screens for Edit Org, Edit Team, Add, Edit & Assign Badges.
- Aligns the Badge screens with other updated interfaces (section layout, heading order, etc)
- Updates badge page styles
- Replaces the use of abbreviated "org" with "organization"
> Add back links

- src/components/edit-team-form.js
Missed during chakra conversion; uses correct input type when mapping org team attributes and extra team attributes, rather than making all inputs for org attributes "text" input type.
This PR:
Develop:
> Use correct input type for edit team attributes

- src/components/edit-team-form.js
- src/components/privacy-policy-form.js
- src/components/profile-attribute-form.js
- src/pages/teams/[id]/edit-profiles.js
- src/pages/teams/[id]/edit.js
This pr:
- ensures that the correct input type is used for the "edit team" attributes
- adds the org name to the team edit "Org attributes" section
- Prevents modification of attribute key_types on team and member attribute forms once the key type has been set.
Contributes to #264
> Enhance profile and team edit forms

- src/components/error-boundary.js
- src/components/profile-form.js
- src/pages/404.js
- src/pages/_app.js
- src/pages/uh-oh.js
This PR:
- adds a React `ErrorBoundary` around components to catch unhandled errors
- styles and renames the uh-oh 404 page to ensure it is used
- catches errors on the `/teams/:id/profile` edit page
Todo:
Contributes to #406
> Add error boundary and update 404 page
