api/teams.js
index.js
lib/team.js
tests/team-api.test.js
tests/team-model.test.js

This allows for the following API:
```
PATCH /api/teams/:id/members
{
add: ['1', '2', '3'],
remove: ['4']
}
```

change addMembers to patch update

---

README.md
example-client/public/profile.js

A couple small fixes needed to get things running (and some arbitrary whitespace deletion my editor decided to do for me).

fix docker command in readme, guard against empty places list in example

---

app/manage/client.js

set owner when creating a client

---

app/lib/team.js
app/manage/index.js
app/manage/permissions/view-team.js
app/manage/teams.js
components/header.js
lib/teams-api.js
package.json
pages/_app.js
pages/index.js
pages/profile.js
pages/team-edit.js
pages/team.js
pages/teams.js
yarn.lock

- Adds Formik for edit form
- Fixes session storage to have the user information in sessionStorage (might want to move this to state management later)
- Also Closes #50 
Note: 
There might be a sync error between token on the server and in the sessionStorage. This will be handled by "unauthorized" responses in the API, but we should have some kind of client side controller for messages and kicking the user back to login when the token is expired.

Editor page

---

components/add-member-form.js
components/table.js
lib/teams-api.js
package.json
pages/team.js
yarn.lock

This pr allows team team moderators to add and remove members of a team.

manage members of a team

---

.circleci/config.yml
app/db/migrations/20190730183820_team-locations.js
app/lib/team.js
components/button.js
components/formikmap.js
package.json
pages/team-edit.js
pages/team.js
yarn.lock

Team location editor

---

app/lib/team.js
app/manage/teams.js
pages/team.js

Closes #56
* Fixes responses when there is an error, using boom properly
* Guards against OSM API 404ing
What this PR doesn't do:
- Guard for an invalid id being added to the team => Request goes through, next get returns `400`
- Guard for an invalid id being part of the team list => get returns `400`

Better error handling from server

---

.env.sample
Dockerfile
README.md
docker-compose.dev.yml
docker.env.sample

This pr:
- shares node_modules between host and container in dev env
- simplifies to only use .env, removing docker.env
- updates docs
closes #14

dev env improvements

---

app/manage/index.js
components/edit-team-form.js
lib/teams-api.js
pages/index.js
pages/team-create.js
pages/team-edit.js

This pr:
- adds a team create page at /teams/create
- refactors the team edit from to a component that is used by the team create/edit pages
- adds a link to create a team on the index page

create team page

---

app/db/knexfile.js
app/index.js
app/lib/team.js
docs/README.md
docs/api.md
docs/api.yml
package.json
yarn.lock

This pr adds openapi (swagger) docs for all api endpoints.
Closes #68.

initial api docs using swagger

---

components/banner.js
pages/_app.js

Added a page banner component for the beta.

Add page banner to app

---

components/button.js
components/layout.js
pages/_app.js
pages/index.js

This PR:
- Adds the beta google form link to the beta banner, and more visible "beta" tag to the banner
- Adds a persistent feedback button across the app

Feature/beta feedback banner + button

---

docker-compose.dev.yml
docker-compose.yml

Update hydra image to oryd/hydra:v1.

---

CHANGELOG.md
app/db/migrations/20200326113917_organization.js
app/lib/organization.js
app/lib/team.js
app/lib/utils.js
app/tests/api/organization-model.test.js

Part of #148 
Initial model for organization
- Adds organization object with new roles: organization owner and manager
- Adds methods to:
- create, read, update, delete organization
- assign new owners and managers
- create a team as part of the organization
- utility functions
- Adds a filter to the team list option to allow for filtering by organization
cc @LanesGood

Organizations model

---

.circleci/config.yml

Update node.js version in circle-ci config.

---

README.md
app/manage/index.js
docs/api.md
docs/api.yml
package.json
yarn.lock

This allows us to test creation of orgs and org teams using the docs UI.

Add orgs to swagger docs

---

Dockerfile

* nodejs dependencies required this

Update Dockerfile image to use FROM node:lts-alpine

---

docker-compose.yml

* this is the production configuration which tells docker-compose to resume the services.

Add restart: always to docker-compose.yml

---

app/lib/organization.js
app/tests/api/organization-model.test.js

#187 
Adjusts organization requests to silently fail duplicate requests

fixes duplicate errors

---

.gitignore
app/db/migrations/20190417173534_init.js
app/db/migrations/20210624112124_team_profiles.js
app/lib/organization.js
app/lib/profile.js
app/lib/team.js
app/lib/utils.js
app/manage/index.js
app/manage/permissions/edit-team.js
app/manage/permissions/edit-user.js
app/manage/permissions/index.js
app/manage/profiles.js
app/tests/api/profile-api.test.js
app/tests/api/profile-model.test.js
app/tests/api/team-model.test.js
package.json
yarn.lock

Adds the ability to add profile metadata to members of teams and organizations.

User profiles

---

pages/team.js

- Fixes the UI for owners so that they can edit a team
- When on an org team page, we get the org staff (API call) and see if the user is an owner. We then surface the edit buttons.
- The API permissions already allow an owner to modify a team, so we only need to change the UI
- With a different user that's an owner of an organization but not a moderator of a team, try editing the team page. 
-

Fix UI for owner

---

pages/_app.js

- Removes the banner at the top of the page
- I removed the content of the `PageBanner` variable
- See that the banner at the top doesn't exist
- 
- Closes #275

Remove the beta banner

---

public/static/icon-close.svg
src/components/button.js
src/components/layout.js
src/components/profile-modal.js
src/components/section-header.js
src/components/sidebar.js
src/components/table.js
src/pages/_app.js
src/pages/index.js
src/pages/organizations/[id]/badges/[badgeId]/index.js
src/pages/organizations/[id]/index.js
src/pages/profile.js
src/pages/teams/[id]/edit.js
src/pages/teams/[id]/index.js
src/pages/teams/index.js
src/styles/global.js

Initial PR to fix styles. Basing off of `v2`
Closes #165

Update global styles, fix scroll and feedback btn

---

src/pages/teams/create.js

Fix regression introduced in v2. 
@LanesGood Ready for review. Please visit the team creation page while signed in with an org member user. You should be able to select the organization the team will be part of.

Fix org team create

---

next.config.js

small fix for vercel deployments

fix for domains in vercel urls

---

cypress/e2e/auth.cy.js
cypress/support/commands/login.js
src/components/sidebar.js
src/pages/api/auth/[...nextauth].js
src/pages/index.js
src/pages/teams/[id]/invitations/[invitationId].js
tests/utils/create-agent.js
tests/utils/get-session-token.js

We move develop from using just OSM to using hydra using the v1 platform for now. Next steps will be to:

Moves the authentication to use auth.mapping.team

---

README.md

Closes https://github.com/developmentseed/osm-teams/issues/341.
@kamicut @batpad ready for review.

Fix auth setup instructions

---

src/pages/teams/[id]/index.js

hot fix for isMember method, as "Edit Profile" button was not showing up

hotfix for isMember method

---

src/models/team.js

Add a count of members to the Paginated Teams table

---

src/pages/index.js

Adds displayname back to welcome page

Add display name to welcome page

---

next.config.js
src/middlewares/base-handler.js
src/pages/api/[[...slug]].js

When testing a 3rd party localhost app, I faced CORS issues. I think this fixes it, but we will have to test on Vercel.
https://vercel.com/guides/how-to-enable-cors#enabling-cors-in-a-next.js-app

allowing CORS in API

---

app/lib/utils.js
src/components/tables/users.js
src/pages/teams/[id]/members-table.js

Uses existing badge component to style the role label in users and members table

Add role label to users and members table

---

CHANGELOG.md

Update CHANGELOG.md with changes introduced by v2.1.0. This is WIP as there is an outstanding PR to be merged to develop.
The list of changes was auto-generated in Github, please let me know if I missed something.
@kamicut should we include a note about authentication?
cc @LanesGood @batpad

Add version 2.1.0 to the changelog

---

src/components/join-link.js
src/pages/organizations/[id]/index.js
src/pages/teams/[id]/index.js

Creates functional external join link component to make use of Chakra UI's `useClipboard` hook.

Create join link component

---

src/components/page-footer.js
src/pages/_app.js
src/pages/privacy.js

Adds privacy policy page to app, and footer with link to all static text pages.

Add footer and privacy policy page
